// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectMentor.Data;

#nullable disable

namespace ProjectMentor.Migrations
{
    [DbContext(typeof(ProjectMentorDbContext))]
    [Migration("20261001214631_AddChatTurns")]
    partial class AddChatTurns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "agent_name", new[] { "planner", "resource_agent", "analysis_agent", "validation_agent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "agent_step_status", new[] { "pending", "running", "success", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "approval_decision_type", new[] { "accepted", "revision_requested" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "guidance_template_type", new[] { "report_outline", "presentation_skeleton", "deployment_checklist" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "milestone_phase", new[] { "title", "design", "build", "documentation", "presentation", "deployment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "milestone_status", new[] { "not_started", "in_progress", "blocked", "done" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "milestone_reminder", "plan_ready", "overdue" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "question_answer_type", new[] { "choice", "multi_select", "short_text", "number", "date" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "resource_type", new[] { "video", "article", "documentation", "course" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "roadmap_request_status", new[] { "submitted", "planning", "pending_approval", "accepted", "revision_requested", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "roadmap_status", new[] { "draft", "pending_approval", "accepted", "superseded", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "student", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow_run_status", new[] { "running", "paused_for_approval", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectMentor.Data.AgentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<AgentName>("AgentName")
                        .HasColumnType("agent_name");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("InputPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("OutputPayload")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<AgentStepStatus>("Status")
                        .HasColumnType("agent_step_status");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId", "StepOrder");

                    b.ToTable("agent_steps", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.AgentWorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoadmapRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<WorkflowRunStatus>("Status")
                        .HasColumnType("workflow_run_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapRequestId");

                    b.HasIndex("Status");

                    b.ToTable("agent_workflow_runs", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ApprovalDecisionType>("Decision")
                        .HasColumnType("approval_decision_type");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("approval_decisions", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.GuidanceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string[]>("ApplicableProjectTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<JsonDocument>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<GuidanceTemplateType>("TemplateType")
                        .HasColumnType("guidance_template_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("guidance_templates", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<MilestonePhase>("Phase")
                        .HasColumnType("milestone_phase");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<MilestoneStatus>("Status")
                        .HasColumnType("milestone_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("RoadmapId", "Status");

                    b.ToTable("milestones", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.MilestoneResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<AgentName>("AttachedBy")
                        .HasColumnType("agent_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("MilestoneId", "ResourceId")
                        .IsUnique();

                    b.ToTable("milestone_resources", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.MilestoneStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<MilestoneStatus>("NewStatus")
                        .HasColumnType("milestone_status");

                    b.Property<MilestoneStatus?>("OldStatus")
                        .HasColumnType("milestone_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("MilestoneId");

                    b.ToTable("milestone_status_history", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NotificationType>("NotificationType")
                        .HasColumnType("notification_type");

                    b.Property<Guid?>("RelatedMilestoneId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMilestoneId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("notifications", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<QuestionAnswerType>("AnswerType")
                        .HasColumnType("question_answer_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DependsOnQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DependsOnValue")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCore")
                        .HasColumnType("boolean");

                    b.Property<JsonDocument>("Options")
                        .HasColumnType("jsonb");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DependsOnQuestionId");

                    b.ToTable("questions", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<JsonDocument>("AnswerValue")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoadmapRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RoadmapRequestId");

                    b.HasIndex("RoadmapRequestId", "QuestionId")
                        .IsUnique();

                    b.ToTable("question_answers", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<ResourceType>("ResourceType")
                        .HasColumnType("resource_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.ToTable("resources", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.ResourceTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ResourceId", "TagId")
                        .IsUnique();

                    b.ToTable("resource_tags", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoadmapRequestId")
                        .HasColumnType("uuid");

                    b.Property<RoadmapStatus>("Status")
                        .HasColumnType("roadmap_status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapRequestId");

                    b.HasIndex("StudentId");

                    b.ToTable("roadmaps", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.RoadmapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<RoadmapRequestStatus>("Status")
                        .HasColumnType("roadmap_request_status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Status");

                    b.ToTable("roadmap_requests", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.ToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgentStepId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("InputParams")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("OutputResult")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AgentStepId");

                    b.ToTable("tool_calls", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("YearOfStudy")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_lower");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.ValidationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId");

                    b.ToTable("validation_results", "public");
                });

            modelBuilder.Entity("ProjectMentor.Data.AgentStep", b =>
                {
                    b.HasOne("ProjectMentor.Data.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("ProjectMentor.Data.AgentWorkflowRun", b =>
                {
                    b.HasOne("ProjectMentor.Data.RoadmapRequest", "RoadmapRequest")
                        .WithMany("WorkflowRuns")
                        .HasForeignKey("RoadmapRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoadmapRequest");
                });

            modelBuilder.Entity("ProjectMentor.Data.ApprovalDecision", b =>
                {
                    b.HasOne("ProjectMentor.Data.User", "Student")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectMentor.Data.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("ProjectMentor.Data.Milestone", b =>
                {
                    b.HasOne("ProjectMentor.Data.Roadmap", "Roadmap")
                        .WithMany("Milestones")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("ProjectMentor.Data.MilestoneResource", b =>
                {
                    b.HasOne("ProjectMentor.Data.Milestone", "Milestone")
                        .WithMany("Resources")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMentor.Data.Resource", "Resource")
                        .WithMany("Milestones")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ProjectMentor.Data.MilestoneStatusHistory", b =>
                {
                    b.HasOne("ProjectMentor.Data.User", "ChangedBy")
                        .WithMany("MilestoneStatusChanges")
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectMentor.Data.Milestone", "Milestone")
                        .WithMany("StatusHistory")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("ProjectMentor.Data.Notification", b =>
                {
                    b.HasOne("ProjectMentor.Data.Milestone", "RelatedMilestone")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedMilestoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectMentor.Data.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedMilestone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectMentor.Data.Question", b =>
                {
                    b.HasOne("ProjectMentor.Data.Question", "DependsOnQuestion")
                        .WithMany("DependentQuestions")
                        .HasForeignKey("DependsOnQuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DependsOnQuestion");
                });

            modelBuilder.Entity("ProjectMentor.Data.QuestionAnswer", b =>
                {
                    b.HasOne("ProjectMentor.Data.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectMentor.Data.RoadmapRequest", "RoadmapRequest")
                        .WithMany("Answers")
                        .HasForeignKey("RoadmapRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("RoadmapRequest");
                });

            modelBuilder.Entity("ProjectMentor.Data.Resource", b =>
                {
                    b.HasOne("ProjectMentor.Data.User", "AddedBy")
                        .WithMany("ResourcesAdded")
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedBy");
                });

            modelBuilder.Entity("ProjectMentor.Data.ResourceTag", b =>
                {
                    b.HasOne("ProjectMentor.Data.Resource", "Resource")
                        .WithMany("Tags")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMentor.Data.Tag", "Tag")
                        .WithMany("Resources")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ProjectMentor.Data.Roadmap", b =>
                {
                    b.HasOne("ProjectMentor.Data.RoadmapRequest", "RoadmapRequest")
                        .WithMany("Roadmaps")
                        .HasForeignKey("RoadmapRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectMentor.Data.User", "Student")
                        .WithMany("Roadmaps")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoadmapRequest");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProjectMentor.Data.RoadmapRequest", b =>
                {
                    b.HasOne("ProjectMentor.Data.User", "Student")
                        .WithMany("RoadmapRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ProjectMentor.Data.ToolCall", b =>
                {
                    b.HasOne("ProjectMentor.Data.AgentStep", "AgentStep")
                        .WithMany("ToolCalls")
                        .HasForeignKey("AgentStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentStep");
                });

            modelBuilder.Entity("ProjectMentor.Data.ValidationResult", b =>
                {
                    b.HasOne("ProjectMentor.Data.AgentWorkflowRun", "WorkflowRun")
                        .WithMany("ValidationResults")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("ProjectMentor.Data.AgentStep", b =>
                {
                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("ProjectMentor.Data.AgentWorkflowRun", b =>
                {
                    b.Navigation("ApprovalDecisions");

                    b.Navigation("Steps");

                    b.Navigation("ValidationResults");
                });

            modelBuilder.Entity("ProjectMentor.Data.Milestone", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Resources");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ProjectMentor.Data.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("DependentQuestions");
                });

            modelBuilder.Entity("ProjectMentor.Data.Resource", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ProjectMentor.Data.Roadmap", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("ProjectMentor.Data.RoadmapRequest", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Roadmaps");

                    b.Navigation("WorkflowRuns");
                });

            modelBuilder.Entity("ProjectMentor.Data.Tag", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ProjectMentor.Data.User", b =>
                {
                    b.Navigation("ApprovalDecisions");

                    b.Navigation("MilestoneStatusChanges");

                    b.Navigation("Notifications");

                    b.Navigation("ResourcesAdded");

                    b.Navigation("RoadmapRequests");

                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
